import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { BubblesBG } from "~/components/bubblesBG";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export const metadata: Metadata = {
  title: "My CV",
  description:
    "Website for showing some of my experience as Software Developer",
  icons: [{ rel: "icon", url: "/happyface-cv.svg" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <BubblesBG />
        {children}
      </body>
    </html>
  );
}
